### ISSUE TITLE
Error when installing MACSr

### ISSUE THREAD

**Issue by zhuyi05** [macs3-project/MACSr#15]
Hello,
I was trying to install MACSr under R4.1.0, Win10. However, it failed with the following error. I am not experienced with R, and wonder if you can give me some advice? I have Rtools installed. Thank you very much!

* installing *source* package 'MACSr' ...
** using non-staged installation via StagedInstall field
./configure.win: line 3: D:/Program: No such file or directory
Warning in system("sh ./configure.win") : exit code 127
ERROR: configuration failed for package 'MACSr'
* removing 'D:/Program Files/R/R-4.1.0/library/MACSr'

The downloaded source packages are in
	‘C:\Users\zhuyi\AppData\Local\Temp\Rtmp65W18b\downloaded_packages’
Warning message:
In .inet_warning(msg) :
  installation of package ‘MACSr’ had non-zero exit status

**Comment by hubentu** [comment]
Hi @zhuyi05 , MACSr is not compatible with Windows system. Please try it with WSL.
